#!/usr/bin/python
import random
import sys


alls = ''

if '-h' in sys.argv or '--help' in sys.argv:
    print("simple password generator tool")
    print("Usage: pgen.py a A 1 @ [-h]")
    sys.exit()

if 'a' in sys.argv:
    alls += 'abcdefghijklnopqrstuvwxyz'
if 'A' in sys.argv:
    alls += 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
if '1' in sys.argv:
    alls += '1234567890'
if '@' in sys.argv:
    alls += '+-/*!&$#?=@<>\\^\"\'|'
    

    

chars = alls
passwords = 10
length = 28
passwords = int(passwords)
length = int(length)
for n in range(passwords):
    password =''
    for i in range(length):
        password += random.choice(chars)
    print(password)
